
version: "2"

services:
  server:
    image: itzg/minecraft-server:java16-openj9
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "500M"
      TZ: "Europe/Paris"
      VIEW_DISTANCE: 10
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "1000"
      MAX_PLAYERS: 10
      TYPE: "BUKKIT"
      PLUGINS_SYNC_UPDATE: "FALSE"
      #WHITELIST: "user1,user2"
    volumes:
      - /data/minecraft-server:/data
      - ./plugins:/plugins

