
version: "3"

services:
  server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "1G"
      TZ: "Europe/Paris"
      VIEW_DISTANCE: 10
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      MAX_PLAYERS: 10
      #WHITELIST: "user1,user2"
    volumes:
      - ./data:/data


